import type { AccessCode, Category, Deck, DeckPlace, Neighborhood, Place, Region } from "./types";

export const regions: Region[] = [
  {
    id: "seongsu",
    name: "성수",
    shortName: "성수",
    displayOrder: 1,
    status: "active",
    mapPin: { x: 249, y: 296 },
  },
  {
    id: "yongsan_hbc",
    name: "용산·후암·해방촌",
    shortName: "용산·후암",
    displayOrder: 2,
    status: "active",
    mapPin: { x: 182, y: 421 },
  },
  {
    id: "yeonnam_mangwon",
    name: "연남·망원",
    shortName: "연남·망원",
    displayOrder: 3,
    status: "active",
    mapPin: { x: 82, y: 335 },
  },
];

export const neighborhoods: Neighborhood[] = [
  ...regions.map((region) => ({
    id: region.id,
    name: region.name,
    displayOrder: region.displayOrder,
    status: region.status,
  })),
  { id: "hbc", name: "해방촌", displayOrder: 101, status: "active" },
  { id: "mullae", name: "문래", displayOrder: 102, status: "active" },
  { id: "seochon", name: "서촌", displayOrder: 103, status: "active" },
];

export const categories: Category[] = [
  { id: "cafe", name: "카페", displayOrder: 1, status: "active" },
  { id: "food", name: "식사", displayOrder: 2, status: "active" },
  { id: "bar", name: "바·라운지", displayOrder: 3, status: "active" },
  { id: "shop", name: "로컬숍", displayOrder: 4, status: "active" },
  { id: "culture", name: "전시·문화", displayOrder: 5, status: "active" },
  { id: "walk", name: "산책·전망", displayOrder: 6, status: "active" },
];

export const accessCodes: AccessCode[] = [
  {
    id: "access-0000",
    email: "earlybird@doripe.kr",
    code: "0000",
    status: "active",
    cohort: "mvp",
    note: "Internal smoke test code",
    createdAt: "2026-05-15T00:00:00+09:00",
    updatedAt: "2026-05-15T00:00:00+09:00",
  },
  {
    id: "access-0529",
    email: "guest@doripe.kr",
    code: "0529",
    status: "active",
    cohort: "mvp",
    createdAt: "2026-05-15T00:00:00+09:00",
    updatedAt: "2026-05-15T00:00:00+09:00",
  },
  {
    id: "access-9999",
    email: "inactive@doripe.kr",
    code: "9999",
    status: "inactive",
    cohort: "mvp",
    createdAt: "2026-05-15T00:00:00+09:00",
    updatedAt: "2026-05-15T00:00:00+09:00",
  },
];

export const decks: Deck[] = [
  {
    id: "yongsan-solo-afternoon",
    regionId: "yongsan_hbc",
    status: "active",
    title: "창가에 앉는 카페",
    shortCopy: "혼자 머물기 좋은 조용한 후암동 코스",
    tags: ["혼자", "차분함"],
    tone: "sunset",
    displayOrder: 1,
  },
  {
    id: "yongsan-photo-lane",
    regionId: "yongsan_hbc",
    status: "active",
    title: "사진이 남는 골목",
    shortCopy: "걷다가 멈추고 싶은 풍경 중심의 루트",
    tags: ["사진", "골목"],
    tone: "lane",
    displayOrder: 2,
  },
  {
    id: "yongsan-night",
    regionId: "yongsan_hbc",
    status: "active",
    title: "밤에 가벼운 한 잔",
    shortCopy: "너무 시끄럽지 않은 저녁 마무리",
    tags: ["밤", "음악"],
    tone: "night",
    displayOrder: 3,
  },
  {
    id: "seongsu-lookout",
    regionId: "seongsu",
    status: "inactive",
    title: "성수의 열린 창",
    shortCopy: "다음 공개를 준비 중인 성수 덱",
    tags: ["준비중"],
    tone: "lookout",
    displayOrder: 1,
  },
];

export const deckPlaces: DeckPlace[] = [
  { deckId: "yongsan-solo-afternoon", placeId: "yongsan-001", displayOrder: 1, featured: true },
  { deckId: "yongsan-solo-afternoon", placeId: "yongsan-002", displayOrder: 2 },
  { deckId: "yongsan-solo-afternoon", placeId: "yongsan-003", displayOrder: 3 },
  { deckId: "yongsan-solo-afternoon", placeId: "yongsan-004", displayOrder: 4 },
  { deckId: "yongsan-solo-afternoon", placeId: "yongsan-005", displayOrder: 5 },
  { deckId: "yongsan-photo-lane", placeId: "yongsan-002", displayOrder: 1, featured: true },
  { deckId: "yongsan-photo-lane", placeId: "yongsan-004", displayOrder: 2 },
  { deckId: "yongsan-photo-lane", placeId: "yongsan-001", displayOrder: 3 },
  { deckId: "yongsan-photo-lane", placeId: "yongsan-003", displayOrder: 4 },
  { deckId: "yongsan-photo-lane", placeId: "yongsan-005", displayOrder: 5 },
  { deckId: "yongsan-night", placeId: "yongsan-005", displayOrder: 1, featured: true },
  { deckId: "yongsan-night", placeId: "yongsan-003", displayOrder: 2 },
  { deckId: "yongsan-night", placeId: "yongsan-004", displayOrder: 3 },
  { deckId: "yongsan-night", placeId: "yongsan-002", displayOrder: 4 },
  { deckId: "yongsan-night", placeId: "yongsan-001", displayOrder: 5 },
];

export const places: Place[] = [
  {
    id: "yongsan-001",
    status: "ready",
    neighborhoodId: "yongsan_hbc",
    subArea: "후암동",
    categoryId: "cafe",
    name: "오르에르",
    shortCopy: "조용히 앉아 창밖을 보기 좋은 후암동의 카페",
    moodTags: ["카페", "데이트", "혼자"],
    bestFor: ["오전 커피", "가벼운 시작"],
    timeTags: ["morning", "afternoon"],
    routeRole: "start",
    lat: 37.55031,
    lng: 126.9769,
    address: "서울 용산구 후암로5길 12",
    nearestStation: "서울역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/yongsan-001",
    coverImageUrl:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    imageUrls: [
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80",
    ],
    imageCredit: "unsplash",
    photoQaStatus: "approved",
    hoursText: "매일 10:00-20:00",
    priceHint: "커피 5천원대",
    stayTimeMinutes: 45,
    editorialNote: "낮은 음악과 밝은 창가가 첫 장소로 부담 없는 카페입니다.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
  {
    id: "yongsan-002",
    status: "ready",
    neighborhoodId: "yongsan_hbc",
    subArea: "후암동",
    categoryId: "walk",
    name: "피크닉",
    shortCopy: "걷다가 쉬어가기 좋은 동네 풍경 포인트",
    moodTags: ["산책", "골목", "사진"],
    bestFor: ["사진", "걷기"],
    timeTags: ["afternoon", "sunset"],
    routeRole: "middle",
    lat: 37.54695,
    lng: 126.98018,
    address: "서울 용산구 후암로 일대",
    nearestStation: "서울역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/yongsan-002",
    coverImageUrl:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    imageUrls: [
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
    ],
    imageCredit: "unsplash",
    photoQaStatus: "approved",
    hoursText: "상시 이용",
    priceHint: "무료",
    stayTimeMinutes: 30,
    editorialNote: "카페에서 나온 뒤 동네 경사를 자연스럽게 받아들이기 좋은 구간입니다.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
  {
    id: "yongsan-003",
    status: "ready",
    neighborhoodId: "yongsan_hbc",
    subArea: "해방촌",
    categoryId: "bar",
    name: "테디뵈르하우스",
    shortCopy: "해방촌 골목 안쪽의 작은 바와 디저트 무드",
    moodTags: ["밤", "음악", "골목"],
    bestFor: ["초저녁", "가벼운 한 잔"],
    timeTags: ["evening", "night"],
    routeRole: "finish",
    lat: 37.54561,
    lng: 126.98474,
    address: "서울 용산구 신흥로 95 일대",
    nearestStation: "녹사평역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/yongsan-003",
    coverImageUrl:
      "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
    imageUrls: [
      "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80",
    ],
    imageCredit: "unsplash",
    photoQaStatus: "approved",
    hoursText: "평일 18:00-24:00",
    priceHint: "디저트 1만원대",
    stayTimeMinutes: 75,
    editorialNote: "골목 특유의 밤공기와 조명이 하루를 정리하기 좋습니다.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
  {
    id: "yongsan-004",
    status: "ready",
    neighborhoodId: "yongsan_hbc",
    subArea: "후암동",
    categoryId: "walk",
    name: "음레코드",
    shortCopy: "음악과 산책 사이에서 잠깐 멈추기 좋은 지점",
    moodTags: ["음악", "산책", "혼자"],
    bestFor: ["쉬어가기", "낮은 템포"],
    timeTags: ["afternoon", "sunset"],
    routeRole: "pause",
    lat: 37.55104,
    lng: 126.98046,
    address: "서울 용산구 후암동 406 일대",
    nearestStation: "서울역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/yongsan-004",
    coverImageUrl:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    imageUrls: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    ],
    imageCredit: "unsplash",
    photoQaStatus: "approved",
    hoursText: "상시 이용",
    priceHint: "무료",
    stayTimeMinutes: 25,
    editorialNote: "걷는 속도를 늦추고 잠시 주변을 둘러보기 좋은 멈춤 지점입니다.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
  {
    id: "yongsan-005",
    status: "ready",
    neighborhoodId: "yongsan_hbc",
    subArea: "해방촌",
    categoryId: "bar",
    name: "해방식당",
    shortCopy: "조용한 음악과 한 잔으로 마무리하는 해방촌의 작은 바",
    moodTags: ["밤", "음악", "한 잔"],
    bestFor: ["마무리", "혼술"],
    timeTags: ["evening", "night"],
    routeRole: "finish",
    lat: 37.54291,
    lng: 126.98732,
    address: "서울 용산구 신흥로0길 7",
    nearestStation: "녹사평역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/yongsan-005",
    coverImageUrl:
      "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=1200&q=80",
    imageUrls: [
      "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=1200&q=80",
    ],
    imageCredit: "unsplash",
    photoQaStatus: "approved",
    hoursText: "매일 19:00-01:00",
    priceHint: "칵테일 1만 2천원대",
    stayTimeMinutes: 70,
    editorialNote: "혼자 앉아도 어색하지 않은 바 좌석과 낮은 조도가 장점입니다.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
];
