import type { AccessCode, Category, Neighborhood, Place } from "./types";

export const neighborhoods: Neighborhood[] = [
  {
    id: "hbc",
    name: "후암동/해방촌",
    displayOrder: 1,
    status: "active",
  },
  {
    id: "mullae",
    name: "문래",
    displayOrder: 2,
    status: "active",
  },
  {
    id: "seochon",
    name: "서촌/원서/계동",
    displayOrder: 3,
    status: "active",
  },
];

export const categories: Category[] = [
  {
    id: "cafe",
    name: "카페",
    displayOrder: 1,
    status: "active",
  },
  {
    id: "food",
    name: "음식",
    displayOrder: 2,
    status: "active",
  },
  {
    id: "bar",
    name: "바/술집",
    displayOrder: 3,
    status: "active",
  },
  {
    id: "shop",
    name: "로컬숍",
    displayOrder: 4,
    status: "active",
  },
  {
    id: "culture",
    name: "전시/문화",
    displayOrder: 5,
    status: "active",
  },
  {
    id: "walk",
    name: "산책/뷰/공간",
    displayOrder: 6,
    status: "active",
  },
];

export const accessCodes: AccessCode[] = [
  {
    id: "access-0000",
    email: "earlybird@doripe.kr",
    code: "0000",
    status: "active",
    cohort: "mvp",
    note: "Internal smoke test code",
    createdAt: "2026-05-15T00:00:00+09:00",
    updatedAt: "2026-05-15T00:00:00+09:00",
  },
  {
    id: "access-0529",
    email: "guest@doripe.kr",
    code: "0529",
    status: "active",
    cohort: "mvp",
    createdAt: "2026-05-15T00:00:00+09:00",
    updatedAt: "2026-05-15T00:00:00+09:00",
  },
  {
    id: "access-9999",
    email: "inactive@doripe.kr",
    code: "9999",
    status: "inactive",
    cohort: "mvp",
    createdAt: "2026-05-15T00:00:00+09:00",
    updatedAt: "2026-05-15T00:00:00+09:00",
  },
];

export const places: Place[] = [
  {
    id: "hbc-001",
    status: "ready",
    neighborhoodId: "hbc",
    subArea: "해방촌 오거리",
    categoryId: "cafe",
    name: "오월의 커피",
    shortCopy: "언덕 산책 전에 들르기 좋은 조용한 카페",
    moodTags: ["차분한", "햇살", "혼자"],
    bestFor: ["오전 커피", "가벼운 대화"],
    timeTags: ["morning", "afternoon"],
    routeRole: "start",
    lat: 37.54144,
    lng: 126.98721,
    address: "서울 용산구 신흥로 20길 7",
    nearestStation: "녹사평역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/hbc-001",
    coverImageUrl: "https://images.doripe.kr/hbc-001-cover.jpg",
    imageUrls: [
      "https://images.doripe.kr/hbc-001-1.jpg",
      "https://images.doripe.kr/hbc-001-2.jpg",
    ],
    imageCredit: "team",
    photoQaStatus: "approved",
    hoursText: "매일 10:00-20:00",
    priceHint: "커피 5천원대",
    stayTimeMinutes: 45,
    editorialNote: "해방촌의 속도를 천천히 맞추기 좋은 첫 지점.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
  {
    id: "hbc-002",
    status: "ready",
    neighborhoodId: "hbc",
    subArea: "소월길",
    categoryId: "walk",
    name: "소월길 전망 산책",
    shortCopy: "남산과 골목 풍경이 겹쳐 보이는 짧은 산책 구간",
    moodTags: ["전망", "골목", "바람"],
    bestFor: ["사진", "걷기"],
    timeTags: ["afternoon", "sunset"],
    routeRole: "middle",
    lat: 37.54302,
    lng: 126.98487,
    address: "서울 용산구 소월로 일대",
    nearestStation: "녹사평역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/hbc-002",
    coverImageUrl: "https://images.doripe.kr/hbc-002-cover.jpg",
    imageUrls: [
      "https://images.doripe.kr/hbc-002-1.jpg",
      "https://images.doripe.kr/hbc-002-2.jpg",
    ],
    imageCredit: "team",
    photoQaStatus: "approved",
    hoursText: "상시 이용",
    priceHint: "무료",
    stayTimeMinutes: 30,
    editorialNote: "카페에서 나온 뒤 동네의 높낮이를 느끼기 좋은 연결점.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
  {
    id: "hbc-003",
    status: "ready",
    neighborhoodId: "hbc",
    subArea: "해방촌 신흥시장",
    categoryId: "bar",
    name: "신흥시장 와인바",
    shortCopy: "저녁 동선의 끝에 두기 좋은 작은 바",
    moodTags: ["저녁", "대화", "은은한"],
    bestFor: ["한 잔", "마무리 코스"],
    timeTags: ["evening", "night"],
    routeRole: "finish",
    lat: 37.54511,
    lng: 126.9859,
    address: "서울 용산구 신흥로 일대",
    nearestStation: "녹사평역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/hbc-003",
    coverImageUrl: "https://images.doripe.kr/hbc-003-cover.jpg",
    imageUrls: [
      "https://images.doripe.kr/hbc-003-1.jpg",
      "https://images.doripe.kr/hbc-003-2.jpg",
    ],
    imageCredit: "team",
    photoQaStatus: "approved",
    hoursText: "화-일 18:00-24:00",
    priceHint: "잔 와인 1만원대",
    stayTimeMinutes: 75,
    editorialNote: "산책 뒤 오늘의 이야기를 정리하기 좋은 마침표.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
];
