import type { AccessCode, Category, Deck, DeckPlace, Neighborhood, Place, Region } from "./types";

export const regions: Region[] = [
  {
    id: "seongsu",
    name: "성수",
    shortName: "성수",
    displayOrder: 1,
    status: "active",
    mapPin: { x: 249, y: 296 },
  },
  {
    id: "yongsan_hbc",
    name: "용산·후암·해방촌",
    shortName: "용산·후암",
    displayOrder: 2,
    status: "active",
    mapPin: { x: 182, y: 421 },
  },
  {
    id: "yeonnam_mangwon",
    name: "연남·망원",
    shortName: "연남·망원",
    displayOrder: 3,
    status: "active",
    mapPin: { x: 82, y: 335 },
  },
];

export const neighborhoods: Neighborhood[] = regions.map((region) => ({
  id: region.id,
  name: region.name,
  displayOrder: region.displayOrder,
  status: region.status,
}));

export const categories: Category[] = [
  { id: "cafe", name: "카페", displayOrder: 1, status: "active" },
  { id: "food", name: "식사", displayOrder: 2, status: "active" },
  { id: "bar", name: "바·술집", displayOrder: 3, status: "active" },
  { id: "shop", name: "로컬숍", displayOrder: 4, status: "active" },
  { id: "culture", name: "전시·문화", displayOrder: 5, status: "active" },
  { id: "walk", name: "산책·전망", displayOrder: 6, status: "active" },
];

export const accessCodes: AccessCode[] = [
  {
    id: "access-0000",
    email: "earlybird@doripe.kr",
    code: "0000",
    status: "active",
    cohort: "mvp",
    note: "Internal smoke test code",
    createdAt: "2026-05-15T00:00:00+09:00",
    updatedAt: "2026-05-15T00:00:00+09:00",
  },
  {
    id: "access-0529",
    email: "guest@doripe.kr",
    code: "0529",
    status: "active",
    cohort: "mvp",
    createdAt: "2026-05-15T00:00:00+09:00",
    updatedAt: "2026-05-15T00:00:00+09:00",
  },
  {
    id: "access-9999",
    email: "inactive@doripe.kr",
    code: "9999",
    status: "inactive",
    cohort: "mvp",
    createdAt: "2026-05-15T00:00:00+09:00",
    updatedAt: "2026-05-15T00:00:00+09:00",
  },
];

export const decks: Deck[] = [
  {
    id: "yongsan-solo-afternoon",
    regionId: "yongsan_hbc",
    status: "active",
    title: "혼자 걷는 오후",
    shortCopy: "카페, 전망 산책, 조용한 바를 잇는 덱",
    tags: ["혼자", "차분함"],
    tone: "sunset",
    displayOrder: 1,
  },
  {
    id: "yongsan-photo-lane",
    regionId: "yongsan_hbc",
    status: "active",
    title: "사진 찍는 골목",
    shortCopy: "빛이 좋은 길과 작은 가게 중심의 덱",
    tags: ["사진", "골목"],
    tone: "lane",
    displayOrder: 2,
  },
  {
    id: "yongsan-night",
    regionId: "yongsan_hbc",
    status: "active",
    title: "저녁의 해방촌",
    shortCopy: "바와 야경으로 마무리하는 짧은 덱",
    tags: ["밤", "음악"],
    tone: "night",
    displayOrder: 3,
  },
  {
    id: "seongsu-lookout",
    regionId: "seongsu",
    status: "inactive",
    title: "성수의 느린 창",
    shortCopy: "다음 공개를 준비 중인 성수 덱",
    tags: ["준비중"],
    tone: "lookout",
    displayOrder: 1,
  },
];

export const deckPlaces: DeckPlace[] = [
  { deckId: "yongsan-solo-afternoon", placeId: "yongsan-001", displayOrder: 1, featured: true },
  { deckId: "yongsan-solo-afternoon", placeId: "yongsan-002", displayOrder: 2 },
  { deckId: "yongsan-solo-afternoon", placeId: "yongsan-003", displayOrder: 3 },
  { deckId: "yongsan-solo-afternoon", placeId: "yongsan-004", displayOrder: 4 },
  { deckId: "yongsan-solo-afternoon", placeId: "yongsan-005", displayOrder: 5 },
];

export const places: Place[] = [
  {
    id: "yongsan-001",
    status: "ready",
    neighborhoodId: "yongsan_hbc",
    subArea: "후암동",
    categoryId: "cafe",
    name: "오월의 커피",
    shortCopy: "후암동 언덕 산책 전에 들르기 좋은 조용한 카페",
    moodTags: ["차분함", "햇살", "혼자"],
    bestFor: ["오전 커피", "가벼운 시작"],
    timeTags: ["morning", "afternoon"],
    routeRole: "start",
    lat: 37.55031,
    lng: 126.9769,
    address: "서울 용산구 후암로35길 12",
    nearestStation: "숙대입구역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/yongsan-001",
    coverImageUrl:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    imageUrls: [
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80",
    ],
    imageCredit: "unsplash",
    photoQaStatus: "approved",
    hoursText: "매일 10:00-20:00",
    priceHint: "커피 5천원대",
    stayTimeMinutes: 45,
    editorialNote: "낮은 음악과 밝은 창가가 첫 장소로 부담 없는 카페입니다.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
  {
    id: "yongsan-002",
    status: "ready",
    neighborhoodId: "yongsan_hbc",
    subArea: "소월길",
    categoryId: "walk",
    name: "소월길 산책",
    shortCopy: "남산과 동네 골목의 높낮이를 천천히 걷는 길",
    moodTags: ["전망", "골목", "바람"],
    bestFor: ["사진", "걷기"],
    timeTags: ["afternoon", "sunset"],
    routeRole: "middle",
    lat: 37.54695,
    lng: 126.98018,
    address: "서울 용산구 소월로 일대",
    nearestStation: "숙대입구역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/yongsan-002",
    coverImageUrl:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    imageUrls: [
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
    ],
    imageCredit: "unsplash",
    photoQaStatus: "approved",
    hoursText: "상시 이용",
    priceHint: "무료",
    stayTimeMinutes: 30,
    editorialNote: "카페에서 나온 뒤 동네의 경사를 자연스럽게 받아들이기 좋은 구간입니다.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
  {
    id: "yongsan-003",
    status: "ready",
    neighborhoodId: "yongsan_hbc",
    subArea: "해방촌",
    categoryId: "bar",
    name: "신흥시장 와인바",
    shortCopy: "시장 골목 안쪽에 숨어 있는 작은 와인바",
    moodTags: ["와인", "골목", "대화"],
    bestFor: ["초저녁", "가벼운 한 잔"],
    timeTags: ["evening", "night"],
    routeRole: "finish",
    lat: 37.54561,
    lng: 126.98474,
    address: "서울 용산구 신흥로 95 일대",
    nearestStation: "녹사평역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/yongsan-003",
    coverImageUrl:
      "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
    imageUrls: [
      "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80",
    ],
    imageCredit: "unsplash",
    photoQaStatus: "approved",
    hoursText: "화-일 18:00-24:00",
    priceHint: "와인 글라스 1만원대",
    stayTimeMinutes: 75,
    editorialNote: "시장 특유의 밀도와 조용한 조명이 하루를 정리하기 좋습니다.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
  {
    id: "yongsan-004",
    status: "ready",
    neighborhoodId: "yongsan_hbc",
    subArea: "후암동",
    categoryId: "walk",
    name: "후암동 전망",
    shortCopy: "서울역과 남산 사이의 도시 풍경을 내려다보는 전망 포인트",
    moodTags: ["전망", "노을", "숨고르기"],
    bestFor: ["해질녘", "잠깐 멈춤"],
    timeTags: ["afternoon", "sunset"],
    routeRole: "pause",
    lat: 37.55104,
    lng: 126.98046,
    address: "서울 용산구 후암동 406 일대",
    nearestStation: "서울역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/yongsan-004",
    coverImageUrl:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    imageUrls: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    ],
    imageCredit: "unsplash",
    photoQaStatus: "approved",
    hoursText: "상시 이용",
    priceHint: "무료",
    stayTimeMinutes: 25,
    editorialNote: "걷는 속도를 낮추고 도시의 층을 바라보기 좋은 짧은 멈춤 지점입니다.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
  {
    id: "yongsan-005",
    status: "ready",
    neighborhoodId: "yongsan_hbc",
    subArea: "해방촌",
    categoryId: "bar",
    name: "해방촌 바",
    shortCopy: "조용한 음악과 야경으로 마무리하는 해방촌의 작은 바",
    moodTags: ["밤", "음악", "야경"],
    bestFor: ["마무리", "혼술"],
    timeTags: ["evening", "night"],
    routeRole: "finish",
    lat: 37.54291,
    lng: 126.98732,
    address: "서울 용산구 신흥로20길 7",
    nearestStation: "녹사평역",
    naverPlaceUrl: "https://map.naver.com/p/entry/place/yongsan-005",
    coverImageUrl:
      "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=1200&q=80",
    imageUrls: [
      "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=1200&q=80",
    ],
    imageCredit: "unsplash",
    photoQaStatus: "approved",
    hoursText: "매일 19:00-01:00",
    priceHint: "칵테일 1만2천원대",
    stayTimeMinutes: 70,
    editorialNote: "혼자 앉아도 어색하지 않은 바 좌석과 낮은 조도가 장점입니다.",
    qaStatus: "ready",
    lastCheckedAt: "2026-05-15",
  },
];
