import type { RouteDefinition } from "./core/router.js";
import {
  createAdminCampaign,
  createAdminCategory,
  createAdminOrganization,
  createAdminPartnership,
  createAdminPlace,
  createAdminTag,
  getAdminAnalytics,
  getAdminCampaign,
  getAdminContent,
  getAdminCurator,
  getAdminDashboard,
  getAdminIntake,
  getAdminMedia,
  getAdminModeration,
  getAdminOrganization,
  getAdminPartnership,
  getAdminPlace,
  getAdminReport,
  getAdminUser,
  importAdminNaverPlace,
  listAdminAudit,
  listAdminCampaigns,
  listAdminCategories,
  listAdminContents,
  listAdminCurators,
  listAdminIntake,
  listAdminMedia,
  listAdminModerationItems,
  listAdminOrganizations,
  listAdminPartnerships,
  listAdminPlaces,
  listAdminReports,
  listAdminTags,
  listAdminUsers,
  updateAdminCampaign,
  updateAdminCategory,
  updateAdminContent,
  updateAdminCurator,
  updateAdminIntake,
  updateAdminMedia,
  updateAdminModeration,
  updateAdminOrganization,
  updateAdminPartnership,
  updateAdminPlace,
  updateAdminReport,
  updateAdminTag,
  updateAdminUser,
} from "./domains/admin.js";
import { createSession, ingestEvents } from "./domains/analytics.js";
import {
  createContent,
  getContent,
  listFeed,
  listMyContents,
  listPlaceContents,
  listProfileContents,
  submitContent,
  updateContent,
} from "./domains/contents.js";
import {
  bootstrap,
  placeDetail,
  publicProfile,
  relatedPlaces,
} from "./domains/discovery.js";
import {
  addCoursePlace,
  createCourse,
  deleteCourse,
  deleteCoursePlace,
  getCourse,
  listCourses,
  replaceCoursePlace,
  updateCourse,
  updateCoursePlace,
} from "./domains/courses.js";
import {
  createBetaApplication,
  createBusinessApplication,
  createCreatorApplication,
  createEventNotificationRequest,
  createTasteNotificationRequest,
} from "./domains/forms.js";
import { completeMediaUpload, createMediaUpload, deleteMedia } from "./domains/media.js";
import {
  getAccount,
  getNotifications,
  getProfile,
  patchProfile,
  putNotifications,
  putOnboarding,
  requestWithdrawal,
} from "./domains/me.js";
import { getOperatorMe } from "./domains/operator.js";
import { deleteSave, listSaves, putSave } from "./domains/saves.js";
import { createShare, getShare, revokeShare } from "./domains/shares.js";
import {
  createComment,
  deleteComment,
  followProfile,
  likeComment,
  likeContent,
  listContentComments,
  listMyFollowing,
  unfollowProfile,
  unlikeComment,
  unlikeContent,
  updateComment,
} from "./domains/social.js";
import { createInquiry, createReport, listMyInquiries, listMyReports } from "./domains/support.js";
import { authConfig, health, readiness } from "./domains/system.js";

export const v1Routes: RouteDefinition[] = [
  { auth: "public", handler: authConfig, method: "GET", operationId: "getAuthConfig", path: "auth/config" },
  { auth: "public", handler: health, method: "GET", operationId: "getHealth", path: "health" },
  { auth: "public", handler: readiness, method: "GET", operationId: "getReadiness", path: "readiness" },
  { auth: "public", handler: bootstrap, method: "GET", operationId: "getBootstrap", path: "bootstrap" },
  { auth: "optional", handler: listFeed, method: "GET", operationId: "listFeed", path: "feed" },
  { auth: "public", handler: placeDetail, method: "GET", operationId: "getPlace", path: "places/:id" },
  { auth: "public", handler: listPlaceContents, method: "GET", operationId: "listPlaceContents", path: "places/:id/contents" },
  { auth: "public", handler: relatedPlaces, method: "GET", operationId: "listRelatedPlaces", path: "places/:id/related" },
  { auth: "optional", handler: getContent, method: "GET", operationId: "getContent", path: "contents/:id" },
  { auth: "user", handler: updateContent, method: "PATCH", operationId: "updateContent", path: "contents/:id" },
  { auth: "public", handler: publicProfile, method: "GET", operationId: "getPublicProfile", path: "profiles/:id" },
  { auth: "public", handler: listProfileContents, method: "GET", operationId: "listProfileContents", path: "profiles/:id/contents" },
  { auth: "user", handler: getAccount, method: "GET", operationId: "getMyAccount", path: "me/account" },
  { auth: "user", handler: getProfile, method: "GET", operationId: "getMyProfile", path: "me/profile" },
  { auth: "user", handler: patchProfile, method: "PATCH", operationId: "updateMyProfile", path: "me/profile" },
  { auth: "user", handler: putOnboarding, method: "PUT", operationId: "putMyOnboarding", path: "me/onboarding" },
  { auth: "user", handler: getNotifications, method: "GET", operationId: "getMyNotifications", path: "me/notifications" },
  { auth: "user", handler: putNotifications, method: "PUT", operationId: "putMyNotifications", path: "me/notifications" },
  { auth: "user", handler: requestWithdrawal, method: "POST", operationId: "requestMyWithdrawal", path: "me/withdrawal" },
  { auth: "user", handler: listSaves, method: "GET", operationId: "listMySaves", path: "me/saves" },
  { auth: "user", handler: putSave, method: "PUT", operationId: "putMySave", path: "me/saves/:targetType/:targetId" },
  { auth: "user", handler: deleteSave, method: "DELETE", operationId: "deleteMySave", path: "me/saves/:targetType/:targetId" },
  { auth: "user", handler: listCourses, method: "GET", operationId: "listMyCourses", path: "courses" },
  { auth: "user", handler: createCourse, method: "POST", operationId: "createCourse", path: "courses" },
  { auth: "optional", handler: getCourse, method: "GET", operationId: "getCourse", path: "courses/:id" },
  { auth: "user", handler: updateCourse, method: "PATCH", operationId: "updateCourse", path: "courses/:id" },
  { auth: "user", handler: deleteCourse, method: "DELETE", operationId: "deleteCourse", path: "courses/:id" },
  { auth: "user", handler: addCoursePlace, method: "POST", operationId: "addCoursePlace", path: "courses/:id/places" },
  { auth: "user", handler: updateCoursePlace, method: "PATCH", operationId: "updateCoursePlace", path: "courses/:id/places/:coursePlaceId" },
  { auth: "user", handler: deleteCoursePlace, method: "DELETE", operationId: "deleteCoursePlace", path: "courses/:id/places/:coursePlaceId" },
  { auth: "user", handler: replaceCoursePlace, method: "POST", operationId: "replaceCoursePlace", path: "courses/:id/places/:coursePlaceId/replace" },
  { auth: "user", handler: followProfile, method: "POST", operationId: "followProfile", path: "profiles/:id/follow" },
  { auth: "user", handler: unfollowProfile, method: "DELETE", operationId: "unfollowProfile", path: "profiles/:id/follow" },
  { auth: "user", handler: listMyFollowing, method: "GET", operationId: "listMyFollowing", path: "me/following" },
  { auth: "user", handler: likeContent, method: "POST", operationId: "likeContent", path: "contents/:id/like" },
  { auth: "user", handler: unlikeContent, method: "DELETE", operationId: "unlikeContent", path: "contents/:id/like" },
  { auth: "public", handler: listContentComments, method: "GET", operationId: "listContentComments", path: "contents/:id/comments" },
  { auth: "user", handler: createComment, method: "POST", operationId: "createComment", path: "contents/:id/comments" },
  { auth: "user", handler: updateComment, method: "PATCH", operationId: "updateComment", path: "comments/:id" },
  { auth: "user", handler: deleteComment, method: "DELETE", operationId: "deleteComment", path: "comments/:id" },
  { auth: "user", handler: likeComment, method: "POST", operationId: "likeComment", path: "comments/:id/like" },
  { auth: "user", handler: unlikeComment, method: "DELETE", operationId: "unlikeComment", path: "comments/:id/like" },
  { auth: "user", handler: createContent, method: "POST", operationId: "createContent", path: "contents" },
  { auth: "user", handler: listMyContents, method: "GET", operationId: "listMyContents", path: "me/contents" },
  { auth: "user", handler: submitContent, method: "POST", operationId: "submitContent", path: "contents/:id/submit" },
  { auth: "user", handler: createMediaUpload, method: "POST", operationId: "createMediaUpload", path: "media/uploads" },
  { auth: "user", handler: completeMediaUpload, method: "POST", operationId: "completeMediaUpload", path: "media/:id/complete" },
  { auth: "user", handler: deleteMedia, method: "DELETE", operationId: "deleteMedia", path: "media/:id" },
  { auth: "user", handler: createInquiry, method: "POST", operationId: "createInquiry", path: "inquiries" },
  { auth: "user", handler: listMyInquiries, method: "GET", operationId: "listMyInquiries", path: "me/inquiries" },
  { auth: "user", handler: createReport, method: "POST", operationId: "createReport", path: "reports" },
  { auth: "user", handler: listMyReports, method: "GET", operationId: "listMyReports", path: "me/reports" },
  { auth: "optional", handler: createSession, method: "POST", operationId: "createAnalyticsSession", path: "sessions" },
  { auth: "optional", handler: ingestEvents, method: "POST", operationId: "createEvents", path: "events" },
  { auth: "public", handler: createBetaApplication, method: "POST", operationId: "createBetaApplication", path: "forms/beta" },
  { auth: "public", handler: createCreatorApplication, method: "POST", operationId: "createCreatorApplication", path: "forms/creator" },
  { auth: "public", handler: createBusinessApplication, method: "POST", operationId: "createBusinessApplication", path: "forms/business" },
  { auth: "public", handler: createTasteNotificationRequest, method: "POST", operationId: "createTasteNotificationRequest", path: "forms/notify-taste" },
  { auth: "public", handler: createEventNotificationRequest, method: "POST", operationId: "createEventNotificationRequest", path: "forms/notify-event" },
  { auth: "user", handler: createShare, method: "POST", operationId: "createShare", path: "shares" },
  { auth: "public", handler: getShare, method: "GET", operationId: "resolveShare", path: "shares/:slug" },
  { auth: "user", handler: revokeShare, method: "POST", operationId: "revokeShare", path: "shares/:slug/revoke" },
  { auth: "operator", handler: getOperatorMe, method: "GET", operationId: "getAdminMe", path: "admin/me" },
  { auth: "operator", handler: getAdminDashboard, method: "GET", operationId: "getAdminDashboard", path: "admin/dashboard" },
  { auth: "operator", handler: listAdminPlaces, method: "GET", operationId: "listAdminPlaces", path: "admin/places" },
  { auth: "operator", handler: createAdminPlace, method: "POST", operationId: "createAdminPlace", path: "admin/places" },
  { auth: "operator", handler: getAdminPlace, method: "GET", operationId: "getAdminPlace", path: "admin/places/:id" },
  { auth: "operator", handler: updateAdminPlace, method: "PATCH", operationId: "updateAdminPlace", path: "admin/places/:id" },
  { auth: "operator", handler: listAdminContents, method: "GET", operationId: "listAdminContents", path: "admin/contents" },
  { auth: "operator", handler: getAdminContent, method: "GET", operationId: "getAdminContent", path: "admin/contents/:id" },
  { auth: "operator", handler: updateAdminContent, method: "PATCH", operationId: "updateAdminContent", path: "admin/contents/:id" },
  { auth: "operator", handler: listAdminModerationItems, method: "GET", operationId: "listAdminModerationItems", path: "admin/moderation" },
  { auth: "operator", handler: getAdminModeration, method: "GET", operationId: "getAdminModeration", path: "admin/moderation/:id" },
  { auth: "operator", handler: updateAdminModeration, method: "PATCH", operationId: "updateAdminModeration", path: "admin/moderation/:id" },
  { auth: "operator", handler: listAdminReports, method: "GET", operationId: "listAdminReports", path: "admin/reports" },
  { auth: "operator", handler: getAdminReport, method: "GET", operationId: "getAdminReport", path: "admin/reports/:id" },
  { auth: "operator", handler: updateAdminReport, method: "PATCH", operationId: "updateAdminReport", path: "admin/reports/:id" },
  { auth: "operator", handler: listAdminUsers, method: "GET", operationId: "listAdminUsers", path: "admin/users" },
  { auth: "operator", handler: getAdminUser, method: "GET", operationId: "getAdminUser", path: "admin/users/:id" },
  { auth: "operator", handler: updateAdminUser, method: "PATCH", operationId: "updateAdminUser", path: "admin/users/:id" },
  { auth: "operator", handler: listAdminCurators, method: "GET", operationId: "listAdminCurators", path: "admin/curators" },
  { auth: "operator", handler: getAdminCurator, method: "GET", operationId: "getAdminCurator", path: "admin/curators/:id" },
  { auth: "operator", handler: updateAdminCurator, method: "PATCH", operationId: "updateAdminCurator", path: "admin/curators/:id" },
  { auth: "operator", handler: listAdminCategories, method: "GET", operationId: "listAdminCategories", path: "admin/categories" },
  { auth: "operator", handler: createAdminCategory, method: "POST", operationId: "createAdminCategory", path: "admin/categories" },
  { auth: "operator", handler: updateAdminCategory, method: "PATCH", operationId: "updateAdminCategory", path: "admin/categories/:id" },
  { auth: "operator", handler: listAdminTags, method: "GET", operationId: "listAdminTags", path: "admin/tags" },
  { auth: "operator", handler: createAdminTag, method: "POST", operationId: "createAdminTag", path: "admin/tags" },
  { auth: "operator", handler: updateAdminTag, method: "PATCH", operationId: "updateAdminTag", path: "admin/tags/:id" },
  { auth: "operator", handler: listAdminMedia, method: "GET", operationId: "listAdminMedia", path: "admin/media" },
  { auth: "operator", handler: getAdminMedia, method: "GET", operationId: "getAdminMedia", path: "admin/media/:id" },
  { auth: "operator", handler: updateAdminMedia, method: "PATCH", operationId: "updateAdminMedia", path: "admin/media/:id" },
  { auth: "operator", handler: importAdminNaverPlace, method: "POST", operationId: "importAdminNaverPlace", path: "admin/imports/naver-place" },
  { auth: "operator", handler: listAdminIntake, method: "GET", operationId: "listAdminIntake", path: "admin/intake/:kind" },
  { auth: "operator", handler: getAdminIntake, method: "GET", operationId: "getAdminIntake", path: "admin/intake/:kind/:id" },
  { auth: "operator", handler: updateAdminIntake, method: "PATCH", operationId: "updateAdminIntake", path: "admin/intake/:kind/:id" },
  { auth: "operator", handler: listAdminOrganizations, method: "GET", operationId: "listAdminOrganizations", path: "admin/organizations" },
  { auth: "operator", handler: createAdminOrganization, method: "POST", operationId: "createAdminOrganization", path: "admin/organizations" },
  { auth: "operator", handler: getAdminOrganization, method: "GET", operationId: "getAdminOrganization", path: "admin/organizations/:id" },
  { auth: "operator", handler: updateAdminOrganization, method: "PATCH", operationId: "updateAdminOrganization", path: "admin/organizations/:id" },
  { auth: "operator", handler: listAdminPartnerships, method: "GET", operationId: "listAdminPartnerships", path: "admin/partnerships" },
  { auth: "operator", handler: createAdminPartnership, method: "POST", operationId: "createAdminPartnership", path: "admin/partnerships" },
  { auth: "operator", handler: getAdminPartnership, method: "GET", operationId: "getAdminPartnership", path: "admin/partnerships/:id" },
  { auth: "operator", handler: updateAdminPartnership, method: "PATCH", operationId: "updateAdminPartnership", path: "admin/partnerships/:id" },
  { auth: "operator", handler: listAdminCampaigns, method: "GET", operationId: "listAdminCampaigns", path: "admin/campaigns" },
  { auth: "operator", handler: createAdminCampaign, method: "POST", operationId: "createAdminCampaign", path: "admin/campaigns" },
  { auth: "operator", handler: getAdminCampaign, method: "GET", operationId: "getAdminCampaign", path: "admin/campaigns/:id" },
  { auth: "operator", handler: updateAdminCampaign, method: "PATCH", operationId: "updateAdminCampaign", path: "admin/campaigns/:id" },
  { auth: "operator", handler: getAdminAnalytics, method: "GET", operationId: "getAdminAnalytics", path: "admin/analytics" },
  { auth: "operator", handler: listAdminAudit, method: "GET", operationId: "listAdminAudit", path: "admin/audit" },
];
